apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: riadflh/node-app-img:latest
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_URL
          value: "redis://redis-main-service.default.svc.cluster.local:6379"
        - name: REDIS_REPLICAS_URL
          value: "redis://redis-replica-service.default.svc.cluster.local:6379"
        - name: PORT
          value: "3000"

--- 

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app
  minReplicas: 1
  maxReplicas: 10 
  targetCPUUtilizationPercentage: 50  

