apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "node-app"
        static_configs:
          - targets: ["node-service.default.svc.cluster.local"]
