apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "node-app"
        static_configs:
          - targets: ["node-service.default.svc.cluster.local"]
      - job_name: "redis-main"
        static_configs:
          - targets: ["redis-main-exporter.default.svc.cluster.local:9121"]
      - job_name: "redis-replica"
        static_configs:
          - targets: ["redis-replica-exporter.default.svc.cluster.local:9121"]




          
          
