apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  labels:
    name: redis-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-replica
  template:
    metadata:
      labels:
        name: redis-replica
    spec:
      containers:
        - name: redis
          image: 'redis:7.2'
          ports:
            - containerPort: 6380
          command:
            - redis-server
          args:
            - "--slaveof"
            - "redis-main-service.default.svc.cluster.local"
            - "6379"
            - "--port"
            - "6380"

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-replica-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-replica
  minReplicas: 2
  maxReplicas: 10 
  targetCPUUtilizationPercentage: 50



