apiVersion: v1
kind: Service
metadata:
  name: redis-main-exporter
spec:
  selector:
    app: redis-main-exporter
  ports:
    - protocol: TCP
      port: 9121
      targetPort: 9121
      
---
      
apiVersion: v1
kind: Service
metadata:
  name: redis-replica-exporter
spec:
  selector:
    app: redis-replica-exporter
  ports:
    - protocol: TCP
      port: 9121
      targetPort: 9121
