apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-main
  labels:
    name: redis-main
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-main
  template:
    metadata:
      labels:
        name: redis-main
    spec:
      containers:
      - name: redis
        image: 'redis:7.2'
        ports:
        - containerPort: 6379

